version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
before_build:
  ps: dotnet restore src/Sociomedia.sln
build:
  verbosity: minimal
after_test:
  - ps: ./publish.ps1
artifacts:
  - path: ./dist/*.zip
deploy:
  provider: GitHub
  auth_token:
    secure: dOx3UobhXopclAAEE0+ZZO+RsLyAyqq9VjPgJ98a1KuZNRAvbKsKr3LL+CgSmnpB
  on:
    APPVEYOR_REPO_TAG: true